# Generated by Django 4.2 on 2026-01-09 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giờ')),
                ('venue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa điểm')),
                ('round', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Vòng đấu')),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tỷ số đội nhà')),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tỷ số đội khách')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.team', verbose_name='Đội khách')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.team', verbose_name='Đội nhà')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='seasons.season', verbose_name='Mùa giải')),
            ],
            options={
                'verbose_name': 'Trận đấu',
                'verbose_name_plural': 'Trận đấu',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Phút ghi bàn')),
                ('goal_type', models.CharField(choices=[('NORMAL', 'Bình thường'), ('PENALTY', 'Penalty'), ('FREE_KICK', 'Đá phạt'), ('HEADER', 'Đánh đầu'), ('OWN_GOAL', 'Phản lưới')], default='NORMAL', max_length=15, verbose_name='Loại bàn thắng')),
                ('assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='players.player', verbose_name='Người kiến tạo')),
                ('for_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='teams.team', verbose_name='Ghi cho đội')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='matches.match', verbose_name='Trận đấu')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='players.player', verbose_name='Người ghi bàn')),
            ],
            options={
                'verbose_name': 'Bàn thắng',
                'verbose_name_plural': 'Bàn thắng',
                'ordering': ['match', 'minute'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('YELLOW', 'Thẻ vàng'), ('RED', 'Thẻ đỏ')], max_length=10, verbose_name='Loại thẻ')),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Phút nhận thẻ')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lý do')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='matches.match', verbose_name='Trận đấu')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='players.player', verbose_name='Cầu thủ')),
            ],
            options={
                'verbose_name': 'Thẻ phạt',
                'verbose_name_plural': 'Thẻ phạt',
                'ordering': ['match', 'minute'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_starter', models.BooleanField(default=True, verbose_name='Đá chính')),
                ('minutes_played', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Số phút thi đấu')),
                ('is_goalkeeper', models.BooleanField(default=False, verbose_name='Là thủ môn')),
                ('goals_conceded', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Số bàn thua')),
                ('clean_sheet', models.BooleanField(default=False, verbose_name='Giữ sạch lưới')),
                ('saves', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Số pha cứu thua')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matches.match', verbose_name='Trận đấu')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='players.player', verbose_name='Cầu thủ')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_match_stats', to='teams.team', verbose_name='Đội')),
            ],
            options={
                'verbose_name': 'Thống kê trận đấu',
                'verbose_name_plural': 'Thống kê trận đấu',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
