# Generated by Django 4.2 on 2026-01-09 03:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Biệt danh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn tham gia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Cầu thủ',
                'verbose_name_plural': 'Cầu thủ',
                'ordering': ['name'],
            },
        ),
    ]
