# Generated by Django 4.2 on 2026-01-09 03:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tên giải')),
                ('type', models.CharField(choices=[('WEEKLY', 'Đá Quanh Năm'), ('LEAGUE', 'Đá Giải')], default='WEEKLY', max_length=10, verbose_name='Loại')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=False, verbose_name='Đang diễn ra')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Mùa giải',
                'verbose_name_plural': 'Mùa giải',
                'ordering': ['-start_date', '-is_active'],
            },
        ),
    ]
