# Generated by Django 4.2 on 2026-01-09 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tên đội')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Logo đội')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Màu áo')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='seasons.season', verbose_name='Thuộc giải')),
            ],
            options={
                'verbose_name': 'Đội bóng',
                'verbose_name_plural': 'Đội bóng',
                'ordering': ['name'],
                'unique_together': {('season', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Số áo')),
                ('position', models.CharField(blank=True, choices=[('GK', 'Thủ môn'), ('DF', 'Hậu vệ'), ('MF', 'Tiền vệ'), ('FW', 'Tiền đạo')], max_length=2, null=True, verbose_name='Vị trí')),
                ('is_captain', models.BooleanField(default=False, verbose_name='Đội trưởng')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='players.player', verbose_name='Cầu thủ')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team', verbose_name='Đội')),
            ],
            options={
                'verbose_name': 'Cầu thủ trong đội',
                'verbose_name_plural': 'Cầu thủ trong đội',
                'unique_together': {('team', 'player')},
            },
        ),
    ]
