# Generated by Django 4.2 on 2026-01-09 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('played', models.PositiveSmallIntegerField(default=0, verbose_name='Số trận')),
                ('won', models.PositiveSmallIntegerField(default=0, verbose_name='Thắng')),
                ('drawn', models.PositiveSmallIntegerField(default=0, verbose_name='Hòa')),
                ('lost', models.PositiveSmallIntegerField(default=0, verbose_name='Thua')),
                ('goals_for', models.PositiveSmallIntegerField(default=0, verbose_name='Bàn thắng')),
                ('goals_against', models.PositiveSmallIntegerField(default=0, verbose_name='Bàn thua')),
                ('goal_diff', models.SmallIntegerField(default=0, verbose_name='Hiệu số')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Điểm')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='seasons.season', verbose_name='Giải đấu')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team', verbose_name='Đội')),
            ],
            options={
                'verbose_name': 'Bảng xếp hạng',
                'verbose_name_plural': 'Bảng xếp hạng',
                'ordering': ['-points', '-goal_diff', '-goals_for'],
                'unique_together': {('season', 'team')},
            },
        ),
    ]
